# Generated by Django 5.0.2 on 2024-02-13 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='base.community'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
