# Generated by Django 5.0.2 on 2024-02-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
